In [1]:
# bài tập 1
a=1
b=2
print(sum)

<built-in function sum>


In [7]:
# 1. Import các thư viện cần thiết
import numpy as np
from scipy import linalg, sparse

# 2. Tạo và in ma trận D
D = np.mat([[3, 4], [5, 6]])
print("Ma trận D:")
print(D)

# 3. Tạo ma trận C với kích thước 5x7 gồm các số ngẫu nhiên
C = np.mat(np.random.random((5, 7)))
print("\nMa trận C:")
print(C)

# 4. Tạo ma trận vuông A 2x2 với số ngẫu nhiên
A = np.mat(np.random.random((2, 2)))
print("\nMa trận A:")
print(A)

# 5. Tạo mảng b chứa số thực và số phức, sau đó chuyển thành ma trận B
b = np.array([[(1 + 5j), 2j, 3j], (4, 5, 6)])
B = np.asmatrix(b)
print("\nMa trận B (chuyển từ mảng có số phức):")
print(B)
# Tạo một ma trận A vuông để minh họa
A = np.array([[2, 1], [5, 3]])

# 6. Chuyển vị và nghịch đảo
print("Ma trận A:")
print(A)

print("\nChuyển vị của A (A.T):")
print(A.T)

print("\nMa trận nghịch đảo của A (A.I hoặc linalg.inv(A)):")
print(np.linalg.inv(A))  # hoặc A.I nếu dùng np.mat

# 8. Ma trận dưới từ đường chéo
M = np.array([[-1, 3, 2],
              [ 0, -2, 1],
              [ 1, 5, -2]])
M_lower = np.tril(M)
print("\nMa trận M:")
print(M)

print("\nMa trận dưới từ đường chéo (np.tril(M)):")
print(M_lower)

# 9. Ma trận trên từ đường chéo
M_upper = np.triu(M)
print("\nMa trận trên từ đường chéo (np.triu(M)):")
print(M_upper)

# 10. Vector và ma trận đường chéo
v_diag = np.diag(M)  # Lấy vector đường chéo
print("\nVector đường chéo (np.diag(M)):")
print(v_diag)

M_diag = np.diag(v_diag)  # Tạo lại ma trận đường chéo từ vector
print("\nMa trận đường chéo từ vector (np.diag(v_diag)):")
print(M_diag)
# Tạo ma trận A 6x6 gồm các số từ 0 đến 35
A = np.reshape(np.arange(36.0), (6, 6))
print("Ma trận A:")
print(A)

# Tạo ma trận đơn vị I6
I6 = np.identity(6)
print("\nMa trận đơn vị I6:")
print(I6)

# Kích thước của A (số phần tử)
print("\nSố phần tử của ma trận A (A.size):", A.size)

# Lấy đường chéo chính của ma trận A
diagonal_A = np.matrix.diagonal(A)
print("\nĐường chéo chính của A:")
print(diagonal_A)

# Tạo ma trận A mới: A = A + I
A = A + I6
print("\nMa trận A sau khi cộng với I (A + I):")
print(A)

# Tính tích của A với 1 vector (ví dụ vector hàng gồm toàn 1)
v = np.ones((6, 1))
product = A @ v
print("\nTích A nhân với vector v:")
print(product)

Ma trận D:
[[3 4]
 [5 6]]

Ma trận C:
[[0.46396802 0.70350388 0.83502852 0.40905878 0.54440772 0.02781443
  0.47680526]
 [0.93694236 0.13699699 0.59321809 0.64092435 0.80407219 0.68184484
  0.44031125]
 [0.13465211 0.52607057 0.80226616 0.9372848  0.89803486 0.99029027
  0.43204907]
 [0.32067662 0.29591783 0.72074373 0.40774743 0.79592983 0.48294773
  0.01065186]
 [0.86288659 0.24704161 0.61972172 0.57652423 0.73786153 0.97640114
  0.07192928]]

Ma trận A:
[[0.19036539 0.13529016]
 [0.05324875 0.76599688]]

Ma trận B (chuyển từ mảng có số phức):
[[1.+5.j 0.+2.j 0.+3.j]
 [4.+0.j 5.+0.j 6.+0.j]]
Ma trận A:
[[2 1]
 [5 3]]

Chuyển vị của A (A.T):
[[2 5]
 [1 3]]

Ma trận nghịch đảo của A (A.I hoặc linalg.inv(A)):
[[ 3. -1.]
 [-5.  2.]]

Ma trận M:
[[-1  3  2]
 [ 0 -2  1]
 [ 1  5 -2]]

Ma trận dưới từ đường chéo (np.tril(M)):
[[-1  0  0]
 [ 0 -2  0]
 [ 1  5 -2]]

Ma trận trên từ đường chéo (np.triu(M)):
[[-1  3  2]
 [ 0 -2  1]
 [ 0  0 -2]]

Vector đường chéo (np.diag(M)):
[-1 -2 -2]

Ma trận

In [9]:
# Tạo lại ma trận A 6x6
A = np.reshape(np.arange(36.0), (6, 6))
print("Ma trận A:")
print(A)

# Tạo vector vecB và nhân với A
vecB = np.array([1., 2., 3., 4., 5., 6.])
C = A.dot(vecB)
print("\nVector vecB:")
print(vecB)
print("\nKết quả C = A.dot(vecB):")
print(C)

# Tạo ma trận D (2x6) và nhân với A
D = np.array([[1., 2., 3., 4., 5., 6.],
              [1., 0., 1., 0., 1., 0.]])
print("\nMa trận D:")
print(D)

E = A.dot(D.T)  # Transpose vì A là (6x6), D.T là (6x2) -> kết quả (6x2)
print("\nKết quả E = A.dot(D.T):")
print(E)

# Tạo ma trận F (6x2)
F = np.array([[1., 1.],
              [2., 0.],
              [3., 1.],
              [4., 0.],
              [5., 1.],
              [6., 0.]])
print("\nMa trận F:")
print(F)

G = A.dot(F)
print("\nKết quả G = A.dot(F):")
print(G)
# 1. Tính tích A × vecB
vecB = np.array([1., 2., 3., 4., 5., 6.])
C = A.dot(vecB)
print("\nVector vecB:")
print(vecB)
print("\nKết quả C = A.dot(vecB):")
print(C)

# 2. Khai báo ma trận D 2x6
D = np.array([[1., 2., 3., 4., 5., 6.],
              [1., 0., 1., 0., 1., 0.]])
print("\nMa trận D:")
print(D)

# 3. Tính tích A × D.T (chuyển vị vì A là 6x6, D là 2x6)
E = A.dot(D.T)
print("\nKết quả E = A.dot(D.T):")
print(E)

# 4. Xây dựng ma trận F kích thước 6x2
F = np.array([[1., 1.],
              [2., 0.],
              [3., 1.],
              [4., 0.],
              [5., 1.],
              [6., 0.]])
print("\nMa trận F:")
print(F)

# 5. Tính tích A × F
G = A.dot(F)
print("\nKết quả G = A.dot(F):")
print(G)
# Ma trận F kích thước 6x2
F = np.array([[1., 1.],
              [2., 0.],
              [3., 1.],
              [4., 0.],
              [5., 1.],
              [6., 0.]])
print("\nMa trận F:")
print(F)

# Tính G = A × F
G = A.dot(F)
print("\nMa trận G = A.dot(F):")
print(G)

# Tính ma trận nghịch đảo của A (nếu khả thi)
try:
    A_inv = np.linalg.inv(A)
    print("\nMa trận nghịch đảo của A:")
    print(A_inv)
except np.linalg.LinAlgError:
    print("\nMa trận A không khả nghịch (không thể lấy nghịch đảo).")

# Tính np.linalg.inv(np.linalg.inv(A))
try:
    A_double_inv = np.linalg.inv(np.linalg.inv(A))
    print("\nKết quả của np.linalg.inv(np.linalg.inv(A)):")
    print(A_double_inv)
except np.linalg.LinAlgError:
    print("\nKhông thể tính np.linalg.inv(np.linalg.inv(A)).")

Ma trận A:
[[ 0.  1.  2.  3.  4.  5.]
 [ 6.  7.  8.  9. 10. 11.]
 [12. 13. 14. 15. 16. 17.]
 [18. 19. 20. 21. 22. 23.]
 [24. 25. 26. 27. 28. 29.]
 [30. 31. 32. 33. 34. 35.]]

Vector vecB:
[1. 2. 3. 4. 5. 6.]

Kết quả C = A.dot(vecB):
[ 70. 196. 322. 448. 574. 700.]

Ma trận D:
[[1. 2. 3. 4. 5. 6.]
 [1. 0. 1. 0. 1. 0.]]

Kết quả E = A.dot(D.T):
[[ 70.   6.]
 [196.  24.]
 [322.  42.]
 [448.  60.]
 [574.  78.]
 [700.  96.]]

Ma trận F:
[[1. 1.]
 [2. 0.]
 [3. 1.]
 [4. 0.]
 [5. 1.]
 [6. 0.]]

Kết quả G = A.dot(F):
[[ 70.   6.]
 [196.  24.]
 [322.  42.]
 [448.  60.]
 [574.  78.]
 [700.  96.]]

Vector vecB:
[1. 2. 3. 4. 5. 6.]

Kết quả C = A.dot(vecB):
[ 70. 196. 322. 448. 574. 700.]

Ma trận D:
[[1. 2. 3. 4. 5. 6.]
 [1. 0. 1. 0. 1. 0.]]

Kết quả E = A.dot(D.T):
[[ 70.   6.]
 [196.  24.]
 [322.  42.]
 [448.  60.]
 [574.  78.]
 [700.  96.]]

Ma trận F:
[[1. 1.]
 [2. 0.]
 [3. 1.]
 [4. 0.]
 [5. 1.]
 [6. 0.]]

Kết quả G = A.dot(F):
[[ 70.   6.]
 [196.  24.]
 [322.  42.]
 [448.  60.]
 [574.  78.]


In [10]:
import numpy as np

# Tạo ma trận A và vector b
A = np.array([[1, 1], [1, 0]])
b = np.array([1, 0])
n = 10

# Nhân liên tiếp A với b trong n lần
for i in range(n):
    b = A.dot(b)
    print(b)

[1 1]
[2 1]
[3 2]
[5 3]
[8 5]
[13  8]
[21 13]
[34 21]
[55 34]
[89 55]


In [11]:
import sympy as sp
from sympy import Symbol, solve

# Khai báo các ẩn số
x1 = Symbol('x1')
x2 = Symbol('x2')
x3 = Symbol('x3')
x4 = Symbol('x4')

# Khai báo các phương trình
pt1 = x4 + 610 - 450 - x1        # tương đương: x4 - x1 + 160 = 0
pt2 = x1 + 400 - x2 - 640        # tương đương: x1 - x2 - 240 = 0
pt3 = x2 + 600 - x3              # tương đương: x2 - x3 + 600 = 0
pt4 = x3 - x4 - 520              # tương đương: x3 - x4 - 520 = 0

# Giải hệ phương trình
nghiem = sp.solve((pt1, pt2, pt3, pt4))

# In nghiệm
print(nghiem)

{x1: x4 + 160, x2: x4 - 80, x3: x4 + 520}
